Repository coala/cEPs, pull requests merged in 2018-05, with the labels that each got.

#119 cEPs/README.md: Fix readme file typo
  README.md
Labels: difficulty/newcomer, importance/low, process/approved, size/XS

#126 change in README.md as per given in the issue #115
  README.md
Labels: difficulty/newcomer, importance/low, process/approved, size/XS

#127 cEP-0010.md: Fix spelling error in the heading
  cEP-0010.md
Labels: difficulty/newcomer, importance/low, process/approved, size/XS

#128 Add MarkdownBear and format existing .md
  .coafile
  README.md
  cEP-0000.md
  cEP-0001.md
  cEP-0002.md
  cEP-0003.md
  cEP-0005.md
  cEP-0006.md
  cEP-0009.md
  cEP-0010.md
  cEP-0012.md
  cEP-0013.md
  cEP-0014.md
Labels: difficulty/low, importance/low, process/approved, size/XL

#145 CODEOWNERS: Add a list of developers
  CODEOWNERS
Labels: difficulty/low, importance/high, process/pending review, size/XS

#123 cEP-0019.md: Meta-review system
  cEP-0019.md
Labels: New cEP, enhancement, process/pending review, size/M

#147 cEP-0010.md: Update cEP to match existing aspects
  cEP-0010.md
Labels: process/pending review, size/M

#155 cEP-0014: Mark status as active
  cEP-0014.md
Labels: process/approved, size/XS

#144 cEP-0025.md: Integrate pyflakes AST
  cEP-0025.md
Labels: New cEP, process/approved, size/M

#157 .coafile: Set max_line_length
  .coafile
  cEP-0019.md
Labels: difficulty/low, importance/high, process/approved, size/XS

#146 cEP-0026.md: Adds optimize caching cEP
  cEP-0026.md
Labels: process/approved, size/S

#150 cEP-0020: Newcomer metrics and Gamification system
  cEP-0020.md
Labels: New cEP, process/approved, size/L, status/STALE

#149 cEP-0027.md: Improve Lint Bear Quality
  cEP-0027.md
Labels: process/approved, size/S
