Repository coala/cEPs, pull requests merged in 2018-06, with the labels that each got.

#139 cEP-0022.md: add cEP for quickstart green mode
  cEP-0022.md
Labels: New cEP, process/approved, size/L

#160 README.md: Include cEP-0027 in the index table
  README.md
Labels: process/approved, size/XS

#167 README.md: Modify cEP position
  README.md
Labels: process/approved, size/XS

#168 cEP-0021.md: Fix pycodestyle errors
  cEP-0021.md
Labels: process/approved, size/XS

#159 Readme.md: Add entry for cEP-0025
  README.md
Labels: process/approved, size/XS

#117 cEP-0017.md: cEP describing design of cib
  cEP-0017.md
Labels: New cEP, process/approved, size/M

#164 README.md: Add green mode cEP
  README.md
Labels: New cEP, enhancement, process/approved, size/XS

#166 README.md: Add Newcomer Gamification cEP
  README.md
Labels: enhancement, process/pending review, size/XS
